/**:
  ros__parameters:
    motor_ids: [13,3,4,15,5,6,11,1,2,17,7,8,9,10]
    motor_calib_offsets: [2011, 2063, 2018, 2046, 2051, 2052, 2031, 2007, 2038, 2052, 2052, 2068, 2057, 2047]
    encode_ticks_per_rad: 652
    max_encoder_value: 4095
    profile_velocity: 120
    profile_acceleration: 30