/**:
  ros__parameters:
    sitting_pose:  
      # Abad joints: slight outward rotation
      [0.2, -0.6, 0.2, -0.6, 0.2, -0.6, 0.2, -0.6,  
      # Head joints: looking forward
      0.0, 0.0,  
      # Knee joints: bent to support sitting
      1.0, 1.0, 1.0, 1.0]

    standing_pose:  
      # Input in order of leg diagram: FL, BL, BR, FR, Head
      # Hip, Abad, knee joints for each leg, then head joints
      [0.5, 0.0, 1.25,
      0.5, 0.0, 1.25,
      0.5, 0.0, -1.25,
      0.5, 0.0, -1.25,
      # Head joints: looking forward
      0.0, -0.25]

    kneeling_pose:  
      # Abad joints: slight outward
      [0.1, -0.3, 0.1, -0.3, 0.1, -0.3, 0.1, -0.3,  
      # Head joints
      0.0, 0.0,  
      # Knee joints: bent more than standing but less than sitting
      0.8, 0.8, 0.8, 0.8]

    lying_pose:  
      # Input in order of leg diagram: FL, BL, BR, FR, Head
      [-1.45, 0.0, 0.0,
      -1.45, 0.0, 0.0,
      -1.45, 0.0, 0.0,
      -1.45, 0.0, 0.0,
      # Head joints: looking forward
      0.0, -0.5]