/**:
  ros__parameters:
    sitting_pose:  
      # Abad joints: slight outward rotation
      [0.2, -0.6, 0.2, -0.6, 0.2, -0.6, 0.2, -0.6,  
      # Head joints: looking forward
      0.0, 0.0,  
      # Knee joints: bent to support sitting
      1.0, 1.0, 1.0, 1.0]

    standing_pose:  
      # Abad joints: neutral
      [0.0, -0.1, 0.0, -0.1, 0.0, -0.1, 0.0, -0.1,  
      # Head joints: forward
      0.0, 0.0,  
      # Knee joints: slightly extended for standing
      0.5, 0.5, 0.5, 0.5]

    kneeling_pose:  
      # Abad joints: slight outward
      [0.1, -0.3, 0.1, -0.3, 0.1, -0.3, 0.1, -0.3,  
      # Head joints
      0.0, 0.0,  
      # Knee joints: bent more than standing but less than sitting
      0.8, 0.8, 0.8, 0.8]

    lying_pose:  
      # Abad joints: neutral
      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  
      # Head joints: down
      -0.2, -0.2,  
      # Knee joints: fully bent, legs relaxed
      1.2, 1.2, 1.2, 1.2]
